language: python
python:
- '2.7'
- '3.3'
- '3.4'
install: pip install tox-travis
script: tox
notifications:
  email: false
after_success: coveralls
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: youtux
  password:
    secure: RDrgT6IZV7ScFYEdLEHPywEgJhKKJr3vK1vk9irDxefFVXf1cXSxNckFfrfXCIk/hzmPEhgS1bndhM261/32Gube250QHCEV4KxYB83kmv2PuUluI+Js8MCkEKKdLbqUon4dWj0cqjRGy/YACCqiaiy9Yl6OGWKQ2dkPZcDsTAKPN59IfwIO35Y3JFdZg5SVWRL0HZTilHLBo/mI4fT9gM2z2+WOxvh9YWhDx/k/qa8q4ARyOB/JSCrc2Ku/k9cT2qdfTKuaiUlVVE6L3uKKHxEhJoqFrTqEvcKw+FJbRZlqsqCXMknETJzR/zkYbDENJLUBk/RAtNHTUBQ/tY7JPB6dpb1ynwOGGX0xOuGUGAkQPi4BYwozKOXlK6J7kSUbAuaVD1sgdSQA2a37633Nbe3hCiewcj4FX1QQiwdszfhWeiZip/BGP47YNZmOlLE0X+cs6R4eWEMb9fYEbeyHud555pf6Xr+6huLY2mgBUTl9KD0XMoMB5+uHPMuDiwX5ztlFGq6w/RPciDd+xpOhQhaHx1rdgGZUnIx22QUNPKDUFSqPytrl9X/BUGbbXKkEvYPoCmJUx5EE0NIdAIjB9xYB6r0p862QSjqd/c2X8KdC+y/MF1oGb2/tJ3tT6gnA1velZjQlQZOaPVfnpQXX9oHU/v4DjYul7V0bzA3DsUg=
  on:
    tags: true
    repo: youtux/test-travis
