# config file for automatic testing at travis-ci.org
language: python

python:
    - "3.4"
    - "3.3"
    - "2.7"

install:
    pip install tox-travis

script:
    # command to run tests and collect test coverage
    tox

notifications:
    email: false

after_success:
    coveralls
